Update convnet_cifar10.py
in data_utils.py
def to_categorical(y, nb_classes):
......
firstly, argument nb_classes should set default value, or Y = to_categorical(Y) in convnet_cifar10.py report err
my running environment, win10 , python3.5 and tensorflow-gpu  1.3.0rc0
secondly, when set Y=  to_categorical(Y, len(Y)) and Y_test = to_categorical(Y_test,len(Y_test)), I get err below again:
ValueError: Cannot feed value of shape (96, 50000) for Tensor 'TargetsData/Y:0', which has shape '(?, 10)'
at last, when I set 
Y = to_categorical(Y,0) and
Y_test = to_categorical(Y_test,0)
all is OK
......
Training Step: 26049  | total loss: 0.36078 | time: 21.465s
| Adam | epoch: 050 | loss: 0.36078 - acc: 0.8761 -- iter: 49920/50000
Training Step: 26050  | total loss: 0.34343 | time: 22.901s
| Adam | epoch: 050 | loss: 0.34343 - acc: 0.8843 | val_loss: 0.71233 - val_acc: 0.8107 -- iter: 50000/50000